services:
  grpc-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: explore-service-grpc-api
    ports:
      - "55003:50050"
    entrypoint: ./main serve grpc
    environment:
      - DB_HOST=
      - DB_USER=root
      - DB_PASS=
      - DB_PORT=
      - GRPC_PORT=50050
      - ENV=dev
