services:
  mysqldb:
    image: mysql:8.4
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: explore_muzz
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  grpc-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: explore-service-grpc-api
    ports:
      - "55003:50050"
    entrypoint: ./main serve grpc
    environment:
      - DB_HOST=mysqldb
      - DB_USER=test
      - DB_PASS=test
      - DB_PORT=3306
      - GRPC_PORT=50050
      - ENV=dev
      - DB_NAME=explore_muzz
    depends_on:
      - mysqldb